import Head from 'next/head'
import Image from 'next/image'

import { Page } from '../components/layout'
import CustomBigCalendar from '../components/calendar/calendar'

export default function Home() {
  return (
    <div >
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <Page title="Events">
          <CustomBigCalendar />
          <br/><br/>

        </Page>
      </main>

    </div>
  )
}
