import Head from 'next/head'
import Image from 'next/image'

import { Page } from '../components/layout'
import LoremIpsumCalendar from '../components/calendar/loremIpsumCalendar'

export default function Home() {
  return (
    <div >
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <Page title="Events">
          <a href="/events">
            Link to HEAL Calendar
          </a>
          
          <LoremIpsumCalendar />
          <br/><br/>

        </Page>
      </main>

    </div>
  )
}
